-------------------------------------------------------------------------------
-- SPF
--
-- A colorscheme for Neovim.
--
-- Thin entry point: applies the scheme and returns its source-of-truth tables
-- { colors, highlights, links }. `:colorscheme spf` ignores the return value;
-- tests loadfile this to apply AND capture the tables. The palette, primitives,
-- and per-section group maps live under lua/spf/ (see lua/spf/init.lua).
-------------------------------------------------------------------------------
return require("spf").apply()
