local c = require("bw.config.colors")

return {
  { name = "DiagnosticError", fg = c.red, bg = c.terminal, styles = {} },
  { name = "DiagnosticSignError", fg = c.red, bg = c.terminal, styles = {} },
  { name = "DiagnosticFloatingError", fg = c.red, bg = c.terminal, styles = {} },
  { name = "DiagnosticUnderlineError", fg = nil, bg = nil, styles = {} },
  { name = "DiagnosticVirtualTextError", fg = c.red, bg = c.terminal, styles = {} },
  { name = "DiagnosticWarn", fg = c.yellow, bg = c.terminal, styles = {} },
  { name = "DiagnosticSignWarn", fg = c.yellow, bg = c.terminal, styles = {} },
  { name = "DiagnosticFloatingWarn", fg = c.yellow, bg = c.terminal, styles = {} },
  { name = "DiagnosticUnderlineWarn", fg = nil, bg = nil, styles = {} },
  { name = "DiagnosticVirtualTextWarn", fg = c.yellow, bg = c.terminal, styles = {} },
  { name = "DiagnosticOk", fg = c.green, bg = c.terminal, styles = {} },
  { name = "DiagnosticSignOk", fg = c.green, bg = c.terminal, styles = {} },
  { name = "DiagnosticFloatingOk", fg = c.green, bg = c.terminal, styles = {} },
  { name = "DiagnosticUnderlineOk", fg = nil, bg = nil, styles = {} },
  { name = "DiagnosticVirtualTextOk", fg = c.green, bg = c.terminal, styles = {} },
  { name = "DiagnosticHint", fg = c.violet, bg = c.terminal, styles = {} },
  { name = "DiagnosticSignHint", fg = c.violet, bg = c.terminal, styles = {} },
  { name = "DiagnosticFloatingHint", fg = c.violet, bg = c.terminal, styles = {} },
  { name = "DiagnosticUnderlineHint", fg = nil, bg = nil, styles = {} },
  { name = "DiagnosticVirtualTextHint", fg = c.violet, bg = c.terminal, styles = {} },
  { name = "DiagnosticInfo", fg = c.blue, bg = c.terminal, styles = {} },
  { name = "DiagnosticSignInfo", fg = c.blue, bg = c.terminal, styles = {} },
  { name = "DiagnosticFloatingInfo", fg = c.blue, bg = c.terminal, styles = {} },
  { name = "DiagnosticUnderlineInfo", fg = nil, bg = nil, styles = {} },
  { name = "DiagnosticVirtualTextInfo", fg = c.blue, bg = c.terminal, styles = {} },
}
